/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;

/**
 *
 * @author Beto
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        lblLastname = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblPhonenumber = new javax.swing.JLabel();
        txtPhonenumber = new javax.swing.JTextField();
        lblPeople = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAdittionalinfo = new javax.swing.JTextField();
        lblTittle = new javax.swing.JLabel();
        txtPeople = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOcassion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 51, 51));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(600, 400));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(null);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblName.setText("Name:");
        getContentPane().add(lblName);
        lblName.setBounds(20, 110, 40, 20);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(110, 110, 100, 20);

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcess);
        btnProcess.setBounds(210, 280, 100, 30);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint);
        btnPrint.setBounds(220, 320, 80, 30);

        lblLastname.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblLastname.setText("Last Name:");
        getContentPane().add(lblLastname);
        lblLastname.setBounds(240, 110, 100, 20);

        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLastname);
        txtLastname.setBounds(330, 110, 100, 20);

        lblPhonenumber.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblPhonenumber.setText("Phone Number:");
        getContentPane().add(lblPhonenumber);
        lblPhonenumber.setBounds(20, 200, 100, 20);
        getContentPane().add(txtPhonenumber);
        txtPhonenumber.setBounds(110, 200, 100, 20);

        lblPeople.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblPeople.setText("#People:");
        getContentPane().add(lblPeople);
        lblPeople.setBounds(20, 150, 60, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Additional Info:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 210, 120, 30);
        getContentPane().add(txtAdittionalinfo);
        txtAdittionalinfo.setBounds(330, 190, 190, 60);

        lblTittle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTittle.setText("          Cup's of Java Reservation");
        lblTittle.setMaximumSize(new java.awt.Dimension(180, 14));
        getContentPane().add(lblTittle);
        lblTittle.setBounds(130, 30, 280, 30);
        getContentPane().add(txtPeople);
        txtPeople.setBounds(110, 150, 30, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Occasion: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 150, 70, 16);
        getContentPane().add(txtOcassion);
        txtOcassion.setBounds(330, 150, 130, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        if(checkFields()){
            collectInfo();
        } else {
            System.out.println("There are empty fields.");
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        printName();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    public class userInfo {
        String name;
        String lastName;
        String phoneNumber;
        String additionalInfo;
        String numberOfPeople;
        String occasion;
    }
    
    ArrayList<userInfo> allNames = new ArrayList();
    
    
    private boolean checkFields(){
        if(txtName.getText() == null || txtName.getText().isEmpty()){
            return false;
        }
        
        
        return true;
    }
    
    private void collectInfo(){
        
        if(!checkFields())
            return;
        
        userInfo newUser = new userInfo();
        
        newUser.name = txtName.getText();
        
        
        newUser.lastName = txtLastname.getText();
        
        
         newUser.phoneNumber = txtPhonenumber.getText();
        
        
        newUser.numberOfPeople = txtPeople.getText();
        
        
        newUser.occasion = txtOcassion.getText();
        
        
        newUser.additionalInfo = txtAdittionalinfo.getText();
        allNames.add(newUser);
        
    }
    
    private void printName(){
        for(int i = 0 ; i < allNames.size() ; i++){
            
            System.out.println("Name: " + allNames.get(i).name);
            System.out.println("Last Name: " + allNames.get(i).lastName);
            System.out.println("Phone Number: " + allNames.get(i).phoneNumber);
            System.out.println("People: " + allNames.get(i).numberOfPeople);
            System.out.println("The Ocassion is: " + allNames.get(i).occasion);
            System.out.println("Additional Info: " + allNames.get(i).additionalInfo);
        }
        
     
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPeople;
    private javax.swing.JLabel lblPhonenumber;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JTextField txtAdittionalinfo;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOcassion;
    private javax.swing.JTextField txtPeople;
    private javax.swing.JTextField txtPhonenumber;
    // End of variables declaration//GEN-END:variables
}
